framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr_FR
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        save_path: '%kernel.cache_dir%/../../sessions'
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 0

    #esi: true
    #fragments: true
    php_errors:
        log: true

    property_info:
        enabled: true