knp_snappy:
    pdf:
        enabled:    true
        binary:     '%kernel.project_dir%%env(WKHTMLTOPDF_PATH)%'
        options:    []
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
